const saveDataRaw = 
`
{
    "version":1,
    "shop":{
        "type":1,
        "maxCustomers":20,
        "timeUntilNextCustomer":14,
        "timeSinceLastCustomer":0,
        "minTimeUntilNextCustomer":7,
        "maxTimeUntilNextCustomer":20,
        "lifeSales":0,
        "lifeCustomers":0,
        "lifeReputation":0,
        "tiles":[
            {
                "type":"tomatoStand",
                "position":{
                    "x":5,
                    "y":5,
                    "z":0.5
                },
                "amount":3
            },
            {
                "type":"tomatoPlant",
                "position":{
                    "x":5,
                    "y":1,
                    "z":0.5
                },
                "amount":3
            },
            {
                "type":"register",
                "position":{
                    "x":-7,
                    "y":-5,
                    "z":0.5
                }
            },
            {
                "type":"recycleBin",
                "position":{
                    "x":-9,
                    "y":-11,
                    "z":0.5
                }
            }
        ],
        "customers":[
            {
                "reputation":0,
                "position":{
                    "x":0,
                    "y":0,
                    "z":0.5
                },
                "rotation":{
                    "x":0,
                    "y":0,
                    "z":0
                },
                "carriedItems":[
                    {
                        "type":"tomato"
                    }
                ],
                "actions":[
                    {
                        "name":"",
                        "type":"",
                        "amount":0,
                        "container":0,
                        "position":{
                            "x":0,
                            "y":0,
                            "z":0
                        }
                    }
                ]
            }
        ],
        "employees":[
            {
                "position":{
                    "x":0,
                    "y":0,
                    "z":0.5
                },
                "rotation":{
                    "x":0,
                    "y":0,
                    "z":0
                },
                "carriedItems":[
                    {
                        "type":"tomato"
                    }
                ],
                "actions":[
                    {

                    }
                ]
            }
        ]
    },
    "player":{
        "money":1000,
        "position":{
            "x":0,
            "y":0,
            "z":0.5
        },
        "rotation":{
            "x":0,
            "y":0,
            "z":0
        },
        "carriedItems":[
            {
                "type":"tomato"
            }
        ]
    }
}
`;

export function getSaveData()
{
    try
    {
        return JSON.parse(localStorage.getItem("shopSave") ?? saveDataRaw);
    }
    catch (exception)
    {
        console.error("An exception occured while loading save data. We will return a default save, and the previous save will be overwritten.", exception);

        return JSON.parse(saveDataRaw);
    }
}